export const MOCK_CALLS = [
  // AI AGENT ANALYSIS
  {
    id: "call_001",
    priority: "P0",
    emergency_type: "Unresponsive Adult",
    caller_number: "+1 (555) 911-0001",
    location: "Calculating loc...",
    summary: "Subject not breathing, collapsed in kitchen, no pulse detected",
    timestamp: "14:24:02",
    status: "ai_agent",
  },
  {
    id: "call_002",
    priority: "P1",
    emergency_type: "Structure Fire",
    caller_number: "+1 (555) 019-2834",
    location: "Near 200 Block, Residential Area",
    summary: "Smoke visible from second story window, family evacuating",
    timestamp: "14:23:15",
    status: "ai_agent",
  },

  // WAITLIST
  {
    id: "call_003",
    priority: "P2",
    emergency_type: "Traffic Accident",
    caller_number: "+1 (555) 882-1920",
    location: "Hwy 101 SB, Exit 42",
    summary: "Minor collision, two vehicles, no injuries reported",
    timestamp: "14:18:00",
    status: "waitlist",
  },
  {
    id: "call_004",
    priority: "P2",
    emergency_type: "Suspicious Activity",
    caller_number: "+1 (555) 334-9090",
    location: "2200 Block, 5th Ave",
    summary: "Individual looking into parked cars with flashlight",
    timestamp: "14:12:45",
    status: "waitlist",
  },
  {
    id: "call_005",
    priority: "P3",
    emergency_type: "Noise Complaint",
    caller_number: "+1 (555) 771-3321",
    location: "889 Oak Ln",
    summary: "Loud music from neighbor's house, ongoing for 2 hours",
    timestamp: "14:05:20",
    status: "waitlist",
  },

  // HUMAN AGENT
  {
    id: "call_006",
    priority: "P0",
    emergency_type: "Cardiac Arrest",
    caller_number: "+1 (555) 998-2121",
    location: "123 Main St, Apt 4B",
    summary: "CPR in progress by family member, subject unresponsive",
    timestamp: "14:22:10",
    status: "human_agent",
  },
  {
    id: "call_007",
    priority: "P1",
    emergency_type: "Domestic Disturbance",
    caller_number: "+1 (555) 442-1002",
    location: "404 Pine St",
    summary: "Verbal escalation reported by neighbor, possible physical altercation",
    timestamp: "14:20:05",
    status: "human_agent",
  },

  // COMPLETED
  {
    id: "call_008",
    priority: "P2",
    emergency_type: "False Alarm",
    caller_number: "+1 (555) 231-5500",
    location: "1500 Wilson Blvd",
    summary: "Caller confirmed accidental alarm trigger, no emergency",
    timestamp: "14:00:01",
    status: "completed",
  },
  {
    id: "call_009",
    priority: "P3",
    emergency_type: "Minor Theft",
    caller_number: "+1 (555) 009-1234",
    location: "Mall Plaza, Sector 4",
    summary: "Report filed for stolen bicycle from rack outside mall",
    timestamp: "13:45:12",
    status: "completed",
  },
  {
    id: "call_010",
    priority: "P3",
    emergency_type: "Cat in Tree",
    caller_number: "+1 (555) 778-9900",
    location: "21 Park Ave",
    summary: "Fire dept assisted, animal safely retrieved",
    timestamp: "13:10:00",
    status: "completed",
  },
];
